version: "3.7"
services:

  app:
    build:
      args:
        user: kleberalv
        uid: 1000
      dockerfile: Dockerfile
    image: php8-apllication-server
    container_name: apllication-server-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - servernetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug

  db:
    image: mariadb:10.5.8
    container_name: application-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./Docker/database:/var/lib/mysql:rw
    networks:
      - servernetwork
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: application-phpmyadmin
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_DATABASE}
      PMA_PORT: ${DB_PORT}
    networks:
      - servernetwork

  nginx:
    image: nginx:alpine
    container_name: application-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./Docker/nginx:/etc/nginx/conf.d
    networks:
      - servernetwork

networks:
  servernetwork:
    driver: bridge
